### PR TITLE
Add support for webpack 5

### PR DESCRIPTION
**Pull request by cshawaus**
Also maintains backwards compatibility with older versions of webpack.

Fixes:
- https://github.com/lodash/lodash-webpack-plugin/issues/167
- https://github.com/lodash/lodash-webpack-plugin/issues/174

### CODE REVIEW

**Comment by cshawaus** [comment]
@jdalton Apologies for the random mention, it would be good to have this looked at soon.

**Comment by natew** [comment]
Bumping this as it's been a few weeks, this would unblock a move to w5 (or at least, avoid us having to use a fork to upgrade)

**Comment by thaoms** [comment]
> Bumping this as it's been a few weeks, this would unblock a move to w5 (or at least, avoid us having to use a fork to upgrade)

Also blocking us to upgrade to v5

**Comment by jcdesousa** [comment]
@jdalton Can we merge this? 🙏

**Comment by joaoces19** [comment]
Also need this merge request approved in order to upgrade to Webpack 5 please!

**Comment by hiddenest** [comment]
@jdalton any updates or has a blocking issues?
we're really waiting for this to upgrade webpack v5 😢

**Comment by natew** [comment]
Anyone here want to start/maintain a fork 😅

**Comment by thaoms** [comment]
I switched to https://www.npmjs.com/package/babel-plugin-lodash. Could no longer wait.

**Comment by vashchukmaksim** [comment]
Anyone who has permission to merge that or we need a fork?

**Comment by cr0cK** [comment]
It's sad that a change of 5 lines (expect package-locks changes) need more than 2 months to be merged (and I'm afraid that it will not be in the following weeks).

Dear maintainer(s), please consider to delegate the maintenance of this project if you don't have the time to do it anymore.

**Comment by skyrex-mark** [comment]
@jdalton

**Comment by atomicpages** [comment]
For the passersby, you can reference this PR in your NPM script version (no fork needed!):

```json
{
  "devDependencies": {
    "lodash-webpack-plugin": "lodash/lodash-webpack-plugin#pull/173/head"
  }
}
```

**Comment by J-Kallunki** [comment]
> For the passersby, you can reference this PR in your NPM script version (no fork needed!):
> 
> ```json
> {
>   "devDependencies": {
>     "lodash-webpack-plugin": "lodash/lodash-webpack-plugin#pull/173/head"
>   }
> }
> ```

When running (with yarn) reports:
```
Error: Cannot find module 'lodash-webpack-plugin'
```

**Comment by impulse** [comment]
A workaround until this gets merged:
```sh
npm i patch-package
```

Add this to `package.json`
```diff
{
  "scripts": {
+    "postinstall": "patch-package",
  }
}
```

Use this patch I created from the PR (place it `patches` dir in your root project path)
https://gist.github.com/impulse/207d0b3e062fcd97b50484e54210685e#file-lodash-webpack-plugin-0-11-5-patch

**Comment by bnjmnt4n** [comment]
Hi, thanks for the PR! This PR prevents an error from being thrown, but doesn't actually solve the root problem: Webpack v5 has a different API. I've pushed d241458, which updates lodash-webpack-plugin for webpack v5 compatibility. I currently don't have npm publish rights, but I'm in the process of getting them, and will release a version bump after. Apologies for the long wait, and I'll post an update when there's any.

**Comment by bnjmnt4n** [comment]
Just released v0.11.6 - let me know if there are any issues.

**Pull request closed without merging**
