### PR TITLE
fix: mapping baseFlatten to head

### PR DESCRIPTION
**Pull request by Crayonn**
mapping baseFlatten to head

### CODE REVIEW

**Comment by Crayonn** [comment]
Compile the _baseFlatten into a head

build like this

**Comment by jdalton** [comment]
I understand how the mapping works. I don't understand how `head` helps you here though.

**Comment by Crayonn** [comment]
> mapping

I change 'head' to '_baseFlatten' in the mapping, then it work for me，and the mapping relationship is correct. 

if it not modified like this，i will close the pull requests. sorry!

**Comment by Crayonn** [comment]
> I understand how the mapping works. I don't understand how `head` helps you here though.

Very happy to point me wrong. 😺

**Comment by jdalton** [comment]
Thanks for the PR @Crayonn!

I don't think we want to map `baseFlatten` to `head` at this time.

**Comment by Crayonn** [comment]
sorry, You've misunderstood.Now it
map baseFlatten to head. I change it, and
make baseFlatten map to baseFlatten

**Pull request closed without merging**
